#!/usr/bin/env node
/** Transactional manager for a career-ops checkout over an external data repo. */
import { execFileSync, spawnSync } from 'child_process';
import {
  existsSync, lstatSync, readFileSync, writeFileSync, mkdirSync, renameSync,
  rmSync, symlinkSync, realpathSync, copyFileSync, readdirSync,
} from 'fs';
import { dirname, join, relative, resolve, sep } from 'path';
import { createHash } from 'crypto';
import { fileURLToPath } from 'url';
import { isMainModule } from './lib/is-main-module.mjs';

export const ROOT = dirname(fileURLToPath(import.meta.url));
export const STATE_FILE = join(ROOT, '.git', 'fork-sync-state.json');
export const MANIFEST_FILE = join(ROOT, 'fork', 'owned-paths.txt');
const LOCAL_PATHS = join(ROOT, 'config', 'local-paths.txt');

const git = (args, cwd = ROOT, options = {}) => execFileSync('git', args, { cwd, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'], ...options }).trim();
const sha = p => existsSync(p) && !lstatSync(p).isDirectory()
  ? createHash('sha256').update(readFileSync(p)).digest('hex') : null;
const inside = (parent, child) => {
  const r = relative(realpathSync(parent), realpathSync(child));
  return r === '' || (!r.startsWith(`..${sep}`) && r !== '..');
};
const lines = text => text.split(/\r?\n/).map(x => x.trim()).filter(x => x && !x.startsWith('#'));

export function dataRoot(root = ROOT, env = process.env) {
  return resolve(env.CAREER_OPS_DATA_ROOT || join(root, '..', 'career-ops-data'));
}

export function ownedPaths(root = ROOT) {
  return lines(readFileSync(join(root, 'fork', 'owned-paths.txt'), 'utf8'));
}

export function writeLocalPaths(root = ROOT) {
  const body = '# Generated by node fork-sync.mjs doctor; edit fork/owned-paths.txt instead.\n' + ownedPaths(root).join('\n') + '\n';
  mkdirSync(join(root, 'config'), { recursive: true });
  writeFileSync(join(root, 'config', 'local-paths.txt'), body);
  return body;
}

function repositoryStatus(repo) {
  const dirty = git(['status', '--porcelain'], repo);
  let unpushed = '';
  try { unpushed = git(['rev-list', '--count', '@{upstream}..HEAD'], repo); }
  catch { unpushed = 'no-upstream'; }
  return { dirty, unpushed };
}

export function discoverOverlays(root = ROOT, external = dataRoot(root)) {
  const tracked = lines(git(['ls-files'], root));
  const candidates = new Set();
  for (const path of tracked) {
    const first = path.split('/')[0];
    const link = join(root, first);
    if (existsSync(link) && lstatSync(link).isSymbolicLink()) candidates.add(first);
  }
  for (const name of readdirSync(root)) {
    const link = join(root, name);
    if (lstatSync(link).isSymbolicLink()) candidates.add(name);
  }
  return [...candidates].sort().map(path => {
    const link = join(root, path);
    const target = realpathSync(link);
    if (!inside(external, target)) throw new Error(`${path}: target escapes data root: ${target}`);
    return { path, target, tracked: tracked.filter(p => p === path || p.startsWith(`${path}/`)) };
  });
}

function setSkip(root, overlays, enabled) {
  const paths = overlays.flatMap(o => o.tracked);
  if (!paths.length) return;
  git(['update-index', enabled ? '--skip-worktree' : '--no-skip-worktree', '--', ...paths], root);
}

function restore(state, { abort = false } = {}) {
  const external = state.dataRoot;
  for (const overlay of state.overlays) {
    for (const item of overlay.files) {
      const materialized = join(ROOT, item.path);
      const destination = join(external, item.path);
      const now = sha(destination);
      if (!abort && now !== item.externalHash) {
        throw new Error(`${item.path}: external file changed during sync; refusing to overwrite`);
      }
      if (!abort && existsSync(materialized)) {
        mkdirSync(dirname(destination), { recursive: true });
        copyFileSync(materialized, destination);
      }
    }
    const saved = join(ROOT, '.git', 'fork-sync-links', overlay.path);
    if (!existsSync(saved)) continue;
    rmSync(join(ROOT, overlay.path), { recursive: true, force: true });
    mkdirSync(dirname(join(ROOT, overlay.path)), { recursive: true });
    renameSync(saved, join(ROOT, overlay.path));
  }
  setSkip(ROOT, state.overlays, true);
  rmSync(join(ROOT, '.git', 'fork-sync-links'), { recursive: true, force: true });
  rmSync(STATE_FILE, { force: true });
}

export function doctor() {
  const external = dataRoot();
  if (!existsSync(external)) throw new Error(`data repository not found: ${external}`);
  git(['rev-parse', '--is-inside-work-tree'], external);
  const overlays = discoverOverlays(ROOT, external);
  writeLocalPaths(ROOT);
  return { ok: true, dataRoot: external, overlays: overlays.map(o => ({ path: o.path, tracked: o.tracked.length })) };
}

function start(ref = 'upstream/main') {
  if (existsSync(STATE_FILE)) throw new Error('a fork-sync transaction already exists; use continue or abort');
  const external = dataRoot();
  for (const [label, repo] of [['code', ROOT], ['data', external]]) {
    const s = repositoryStatus(repo);
    if (s.dirty) throw new Error(`${label} repository is dirty; commit and push it before sync`);
    if (s.unpushed !== '0') throw new Error(`${label} repository is not fully pushed (${s.unpushed})`);
  }
  const overlays = discoverOverlays(ROOT, external);
  const incoming = new Set(lines(git(['ls-tree', '-r', '--name-only', ref], ROOT)));
  for (const overlay of overlays) {
    overlay.tracked = [...new Set([
      ...overlay.tracked,
      ...[...incoming].filter(p => p === overlay.path || p.startsWith(`${overlay.path}/`)),
    ])].sort();
    overlay.files = overlay.tracked.map(path => ({ path, externalHash: sha(join(external, path)) }));
  }
  const state = { version: 1, phase: 'detaching', ref, dataRoot: external, head: git(['rev-parse', 'HEAD']), overlays };
  writeFileSync(STATE_FILE, JSON.stringify(state, null, 2));
  setSkip(ROOT, overlays, false);
  mkdirSync(join(ROOT, '.git', 'fork-sync-links'), { recursive: true });
  for (const overlay of overlays) {
    const saved = join(ROOT, '.git', 'fork-sync-links', overlay.path);
    mkdirSync(dirname(saved), { recursive: true });
    renameSync(join(ROOT, overlay.path), saved);
    for (const path of overlay.tracked) {
      const out = spawnSync('git', ['show', `HEAD:${path}`], { cwd: ROOT, encoding: null });
      if (out.status !== 0) continue;
      const dest = join(ROOT, path);
      mkdirSync(dirname(dest), { recursive: true });
      writeFileSync(dest, out.stdout);
    }
  }
  state.phase = 'merging';
  writeFileSync(STATE_FILE, JSON.stringify(state, null, 2));
  const merged = spawnSync('git', ['merge', '--no-ff', ref], { cwd: ROOT, stdio: 'inherit' });
  if (merged.status !== 0) return { ok: false, conflict: true, message: 'resolve conflicts, git add them, then run continue' };
  restore(state);
  return { ok: true, merged: ref };
}

function continueSync() {
  if (!existsSync(STATE_FILE)) throw new Error('no fork-sync transaction exists');
  const state = JSON.parse(readFileSync(STATE_FILE, 'utf8'));
  if (git(['diff', '--name-only', '--diff-filter=U'])) throw new Error('unresolved merge conflicts remain');
  if (existsSync(join(ROOT, '.git', 'MERGE_HEAD'))) git(['commit', '--no-edit']);
  restore(state);
  return { ok: true, continued: true };
}

function abortSync() {
  if (!existsSync(STATE_FILE)) throw new Error('no fork-sync transaction exists');
  const state = JSON.parse(readFileSync(STATE_FILE, 'utf8'));
  if (existsSync(join(ROOT, '.git', 'MERGE_HEAD'))) spawnSync('git', ['merge', '--abort'], { cwd: ROOT, stdio: 'inherit' });
  restore(state, { abort: true });
  return { ok: true, aborted: true };
}

const isMain = isMainModule(import.meta.url);
if (isMain) {
  try {
    const [command = 'doctor', ref] = process.argv.slice(2);
    const result = command === 'doctor' ? doctor()
      : command === 'setup' ? { ok: true, localPaths: writeLocalPaths(ROOT).split('\n').filter(Boolean).length - 1 }
      : command === 'start' ? start(ref)
      : command === 'continue' ? continueSync()
      : command === 'abort' ? abortSync()
      : (() => { throw new Error('usage: node fork-sync.mjs setup|doctor|start [ref]|continue|abort'); })();
    console.log(JSON.stringify(result, null, 2));
    if (result.conflict) process.exitCode = 2;
  } catch (error) {
    console.error(`fork-sync: ${error.message}`);
    process.exitCode = 1;
  }
}
